(() => {
  const bank = window.QUESTION_BANK;
  const $ = (id) => document.getElementById(id);
  const ui = ['modeSelect','categorySelect','difficultySelect','nextQuestion','answerInput','submitAnswer','showAnswer','questionCategory','questionDifficulty','questionText','followUp','reviewPanel','scoreBadge','userAnswerDisplay','referenceAnswer','feedbackText','keywordChips','wordCount','timer','bankCount','answeredCount','averageScore','nextAfterReview','resetProgress'].reduce((a,id)=>(a[id]=$(id),a),{});
  const storageKey = 'digital-ic-interview-progress-v1';
  let state = JSON.parse(localStorage.getItem(storageKey) || '{"records":{}}');
  let current = null, startedAt = null, tick = null;
  const categories = [...new Set(bank.map(q=>q.category))];
  ui.categorySelect.innerHTML = '<option value="all">全部方向</option>' + categories.map(x=>`<option value="${x}">${x}</option>`).join('');
  function save(){localStorage.setItem(storageKey,JSON.stringify(state));}
  function stats(){const rows=Object.values(state.records);ui.bankCount.textContent=bank.length;ui.answeredCount.textContent=rows.length;ui.averageScore.textContent=rows.length?`${Math.round(rows.reduce((s,x)=>s+x.score,0)/rows.length)}%`:'—';}
  function timer(){if(!startedAt)return;const s=Math.floor((Date.now()-startedAt)/1000);ui.timer.textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
  function candidateList(){let list=bank.filter(q=>(ui.categorySelect.value==='all'||q.category===ui.categorySelect.value)&&(ui.difficultySelect.value==='all'||q.difficulty===ui.difficultySelect.value));if(ui.modeSelect.value==='mistakes'){list=list.filter(q=>state.records[q.question]?.score<70);if(!list.length) list=bank.filter(q=>!state.records[q.question]||state.records[q.question].score<70);}return list;}
  function startQuestion(){let list=candidateList();if(!list.length){alert('当前筛选条件没有题目。请调整方向或难度。');return;}const unseen=list.filter(q=>!state.records[q.question]);const pool=unseen.length?unseen:list;current=pool[Math.floor(Math.random()*pool.length)];ui.questionCategory.textContent=`${current.category} · ${current.source||'资料题库'}`;ui.questionDifficulty.textContent=current.difficulty;ui.questionText.textContent=current.question;ui.followUp.textContent=`追问：${current.followUp}`;ui.answerInput.value='';ui.wordCount.textContent='0 字';ui.answerInput.disabled=false;ui.submitAnswer.disabled=false;ui.showAnswer.disabled=false;ui.reviewPanel.classList.add('hidden');startedAt=Date.now();clearInterval(tick);tick=setInterval(timer,1000);timer();ui.answerInput.focus();ui.nextQuestion.textContent='换一题 →';}
  function review(showOnly=false){if(!current)return;const raw=ui.answerInput.value.trim();if(!showOnly&&!raw){ui.answerInput.focus();return;}const normalized=raw.toLowerCase();const hits=current.keywords.filter(k=>normalized.includes(k.toLowerCase()));const score=showOnly?0:Math.round(Math.min(100, (hits.length/current.keywords.length)*82 + Math.min(raw.length/180,1)*18));const missing=current.keywords.filter(k=>!hits.includes(k));state.records[current.question]={score,at:Date.now()};save();stats();clearInterval(tick);ui.userAnswerDisplay.textContent=showOnly?'（本题未作答，建议先自行组织答案再查看参考。）':raw;ui.referenceAnswer.textContent=current.answer;ui.scoreBadge.textContent=showOnly?'参考答案':`${score}% 匹配`;let feedback;if(showOnly) feedback='请用参考答案复盘：先说定义，再解释原理，最后落到工程风险或方案。';else if(score>=80) feedback='回答覆盖较完整，已具备清晰的面试表达骨架。下一步可以补充一个实际项目或波形/时序例子，让答案更有说服力。';else if(score>=50) feedback=`核心方向正确，但建议补足这些面试关键词：${missing.slice(0,4).join('、')}。回答时先给结论，再分点展开。`;else feedback=`目前信息不足。可围绕“定义—关键机制—风险/方案”展开，尤其补充：${missing.slice(0,5).join('、')}。`;ui.feedbackText.textContent=feedback;ui.keywordChips.innerHTML=current.keywords.map(k=>`<span class="chip ${hits.includes(k)?'hit':'miss'}">${hits.includes(k)?'✓':'○'} ${k}</span>`).join('');ui.reviewPanel.classList.remove('hidden');ui.reviewPanel.scrollIntoView({behavior:'smooth',block:'start'});}
  ui.nextQuestion.addEventListener('click',startQuestion);ui.nextAfterReview.addEventListener('click',startQuestion);ui.submitAnswer.addEventListener('click',()=>review(false));ui.showAnswer.addEventListener('click',()=>review(true));ui.answerInput.addEventListener('input',()=>ui.wordCount.textContent=`${ui.answerInput.value.length} 字`);ui.resetProgress.addEventListener('click',()=>{if(confirm('确认清除本浏览器中的练习记录？')){state={records:{}};save();stats();}});ui.modeSelect.addEventListener('change',()=>{ui.categorySelect.disabled=ui.modeSelect.value==='mistakes';});stats();
})();
